<?php
/**
 * Created by PhpStorm.
 * User: andrii
 * Date: 15.08.18
 * Time: 16:09
 */

namespace app\modules\admin\components;


use yii\base\Widget;

class AdminMainHeaderWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('adminMainHeader');
    }
}