<?php
/**
 * Created by PhpStorm.
 * User: andrii
 * Date: 15.08.18
 * Time: 15:48
 */
namespace app\modules\admin\components;

class AdminMainSidebarWidget extends \yii\base\Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('adminMainSidebar');
    }
}