<?php
/**
 * Created by PhpStorm.
 * User: andrii
 * Date: 07.08.18
 * Time: 17:54
 */

namespace app\components;


use yii\base\Widget;

class ChartDataWidget extends Widget
{
    public $roulettes;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }




    public function run()
    {
        return $this->render('chartData', ['roulettes' => $this->getData()]);
    }


    public function getData()
    {
        $arrayParent = [];

        foreach ($this->roulettes as $roulette){
            $arrayChild = [];
            if ($roulette->rouletteData) {
                foreach ($roulette->rouletteData as $data) {
                    $arrayChild[] = $data->measurement;
                }

            }
            $arrayParent[] = array_reverse($arrayChild);
        }

        return $arrayParent;

    }
}