<?php
/**
 * Created by PhpStorm.
 * User: andrii
 * Date: 27.08.18
 * Time: 15:44
 */

namespace app\components;


use yii\base\Widget;

class FlashMessageWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('flashMessage');
    }
}