<?php
/**
 * Created by PhpStorm.
 * User: andrii
 * Date: 10.12.18
 * Time: 15:55
 */

namespace app\components;


use yii\base\Widget;

class LoadingModalWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('loadingModal');
    }
}