<?php
/**
 * Created by PhpStorm.
 * User: andrii
 * Date: 24.07.18
 * Time: 17:25
 */

namespace app\components;

use yii\base\Widget;

class MainNavbarWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('mainNavbar');
    }
}