<?php
/**
 * Created by PhpStorm.
 * User: andrii
 * Date: 03.08.18
 * Time: 17:42
 */

namespace app\components;


use yii\base\Widget;

class ModalDisciplineInfoWidget extends Widget
{
    public $discipline;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('modalDisciplineInfo', ['discipline' => $this->discipline]);
    }


}