<?php
/**
 * Created by PhpStorm.
 * User: andrii
 * Date: 01.08.18
 * Time: 10:56
 */

namespace app\components;


use yii\base\Widget;

class PresetsListWidget extends Widget
{
    public $presets;
    public $purpose;

    const PURPOSE_EDIT = 0;
    const PURPOSE_START = 1;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->purpose = $this->purpose ??  self::PURPOSE_EDIT;


    }

    public function run()
    {
        return $this->render('presetsList', [
            'presets' => $this->presets,
            'purpose' => $this->purpose
        ]);
    }

}