<?php
/**
 * Created by PhpStorm.
 * User: andrii
 * Date: 01.08.18
 * Time: 10:56
 */

namespace app\components;


use yii\base\Widget;

class PresetsListWidget extends Widget
{
    public $presets;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('presetsList', ['presets' => $this->presets]);
    }

}