<?php
/**
 * Created by PhpStorm.
 * User: andrii
 * Date: 31.07.18
 * Time: 15:31
 */

namespace app\components;


use yii\base\Widget;

class PresetItemsListWidget extends Widget
{

    public $preset;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('presetItemsList', ['preset' => $this->preset]);
    }


}