<?php
/**
 * Created by PhpStorm.
 * User: andrii
 * Date: 03.08.18
 * Time: 15:02
 */

namespace app\components;


use yii\base\Widget;

class SetsListWidget extends Widget
{
    public $sets;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('setsList', ['sets' => $this->sets]);
    }
}