<?php
/**
 * Created by PhpStorm.
 * User: andrii
 * Date: 24.08.18
 * Time: 23:07
 */

namespace app\components;


use yii\base\Widget;

class StatsChartWidget extends Widget
{
    public $data;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }


    public function run()
    {
        return $this->render('statsChart', ['data' => $this->data]);
    }
}