<?php
/**
 * Created by PhpStorm.
 * User: andrii
 * Date: 03.08.18
 * Time: 16:17
 */

namespace app\components;


use yii\base\Widget;

class WorkingDataListWidget extends Widget
{
    public $working;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('workingDataList', ['working' => $this->working]);
    }
}